const FUEL_MAPPING = Dict(
    "Black Coal" => ThermalFuels.COAL,
    "Brown Coal" => ThermalFuels.COAL,
    "Gas" => ThermalFuels.NATURAL_GAS,
    "Liquid Fuel" => ThermalFuels.DISTILLATE_FUEL_OIL,
    "Water" => ThermalFuels.OTHER,
    "Solar" => ThermalFuels.OTHER,
    "Wind" => ThermalFuels.OTHER,
)

const FUEL_PRICES = Dict(
    "Black Coal" => 9.0,
    "Brown Coal" => 9.0,
    "Gas" => 17.0,
    "Liquid Fuel" => 13.0,
    "Water" => 0.0,
    "Solar" => 0.0,
    "Wind" => 0.0,
)

const PM_MAPPING = Dict(
    "Steam Sub Critical" => PrimeMovers.ST,
    "Steam Super Critical" => PrimeMovers.ST,
    "Biomass" => PrimeMovers.ST,
    "CCGT" => PrimeMovers.CC,
    "CCGT Cogen" => PrimeMovers.CC,
    "CCGT - Gas Turbine" => PrimeMovers.CA,
    "CCGT - Steam Turbine" => PrimeMovers.CA,
    "OCGT" => PrimeMovers.GT,
    "Gas-powered steam turbine" => PrimeMovers.GT,
    "Reciprocating Engine" => PrimeMovers.IC,
    "Hydro" => PrimeMovers.HY,
    "Large scale Solar PV" => PrimeMovers.PVe,
    "Wind" => PrimeMovers.WT,
    "Pumped Hydro" => PrimeMovers.PS,
)

const AEMO_PM_MAPPING = Dict(
    "Natural Gas (Pipeline)" => PrimeMovers.CC,
    "Coal seam methane" => PrimeMovers.CC,
    "Coal Seam Methane" => PrimeMovers.CC,
    "Hydro" => PrimeMovers.HY,
    "Wind" => PrimeMovers.WT,
    "Solar" => PrimeMovers.PVe,
    "Brown coal" => PrimeMovers.ST,
    "Black coal" => PrimeMovers.ST,
    "Battery Storage" => PrimeMovers.BA,
    "Diesel oil" => PrimeMovers.IC,
    "Kerosene - non aviation" => PrimeMovers.GT,
    "Landfill biogas methane" => PrimeMovers.CC,
    "Other Biofuels" => PrimeMovers.CC,
    "Bagasse" => PrimeMovers.CC,
    "Coal mine waste gas" => PrimeMovers.CC,
    "Ethane" => PrimeMovers.GT,
    "Biomass and industrial materials" => PrimeMovers.IC,
    "Primary solid biomass fuels" => PrimeMovers.IC,
    "Other solid fossil fuels" => PrimeMovers.IC,
    missing => missing,
)

const AEMO_FUEL_MAPPING = Dict(
    "Black coal" => ThermalFuels.COAL,
    "Brown coal" => ThermalFuels.COAL,
    "Natural Gas (Pipeline)" => ThermalFuels.NATURAL_GAS,
    "Coal seam methane" => ThermalFuels.OTHER_GAS,
    "Coal Seam Methane" => ThermalFuels.OTHER_GAS,
    "Kerosene - non aviation" => ThermalFuels.DISTILLATE_FUEL_OIL,
    "Diesel oil" => ThermalFuels.DISTILLATE_FUEL_OIL,
    "Solar" => ThermalFuels.OTHER,
    "Wind" => ThermalFuels.OTHER,
    "Hydro" => ThermalFuels.OTHER,
    "Battery Storage" => ThermalFuels.OTHER,
    "Landfill biogas methane" => ThermalFuels.AG_BIPRODUCT,
    "Other Biofuels" => ThermalFuels.AG_BIPRODUCT,
    "Primary solid biomass fuels" => ThermalFuels.AG_BIPRODUCT,
    "Bagasse" => ThermalFuels.AG_BIPRODUCT,
    "Coal mine waste gas" => ThermalFuels.OTHER_GAS,
    "Ethane" => ThermalFuels.OTHER_GAS,
    "Biomass and industrial materials" => ThermalFuels.AG_BIPRODUCT,
    "Other solid fossil fuels" => ThermalFuels.WASTE_COAL,
    missing => missing,
)

const NEMWEB_TABLE_SCHEMA = Dict(
    :DISPATCHREGIONSUM => [
        :SETTLEMENTDATE,
        :REGIONID,
        :TOTALDEMAND,
        :AVAILABLEGENERATION,
        :AVAILABLELOAD,
    ],
    :INTERCONNECTOR => [
        :INTERCONNECTORID,
        :REGIONFROM,
        :REGIONTO,
    ],
    :INTERCONNECTORCONSTRAINT => [
        :FROMREGIONLOSSSHARE,
        :EFFECTIVEDATE,
        :VERSIONNO,
        :INTERCONNECTORID,
        :MAXMWIN,
        :MAXMWOUT,
        :LOSSCONSTANT,
        :LOSSFLOWCOEFFICIENT,
        :IMPORTLIMIT,
        :EXPORTLIMIT,
        :ICTYPE,
    ],
    :DUDETAIL => [
        :EFFECTIVEDATE,
        :DUID,
        :VERSIONNO,
        :CONNECTIONPOINTID,
        :VOLTLEVEL,
        :REGISTEREDCAPACITY,
        :AGCCAPABILITY,
        :DISPATCHTYPE,
        :MAXCAPACITY,
        :STARTTYPE,
        :NORMALLYONFLAG,
        :SPINNINGRESERVEFLAG,
        :INTERMITTENTFLAG,
        :SEMISCHEDULE_FLAG,
        :MAXRATEOFCHANGEUP,
        :MAXRATEOFCHANGEDOWN,
        :ADG_ID,
        :MINCAPACITY,
        :REGISTEREDMINCAPACITY,
        :MAXRATEOFCHANGEUP_LOAD,
        :MAXRATEOFCHANGEDOWN_LOAD,
        :MAXSTORAGECAPACITY,
        :STORAGEIMPORTEFFICIENCYFACTOR,
        :STORAGEEXPORTEFFICIENCYFACTOR,
        :MIN_RAMP_RATE_UP,
        :MIN_RAMP_RATE_DOWN,
        :LOAD_MIN_RAMP_RATE_UP,
        :LOAD_MIN_RAMP_RATE_DOWN,
        :AGGREGATED,
    ],
    :DUDETAILSUMMARY => [
        :DUID,
        :START_DATE,
        :END_DATE,
        :DISPATCHTYPE,
        :CONNECTIONPOINTID,
        :REGIONID,
        :STATIONID,
        :TRANSMISSIONLOSSFACTOR,
        :STARTTYPE,
        :DISTRIBUTIONLOSSFACTOR,
        :MINIMUM_ENERGY_PRICE,
        :MAXIMUM_ENERGY_PRICE,
        :SCHEDULE_TYPE,
        :MIN_RAMP_RATE_UP,
        :MIN_RAMP_RATE_DOWN,
        :MAX_RAMP_RATE_UP,
        :MAX_RAMP_RATE_DOWN,
        :IS_AGGREGATED,
        :LOAD_MINIMUM_ENERGY_PRICE,
        :LOAD_MAXIMUM_ENERGY_PRICE,
        :LOAD_MIN_RAMP_RATE_UP,
        :LOAD_MIN_RAMP_RATE_DOWN,
        :LOAD_MAX_RAMP_RATE_UP,
        :LOAD_MAX_RAMP_RATE_DOWN,
        :SECONDARY_TLF,
    ],
    :DUALLOC => [
        :VERSIONNO,
        :DUID,
        :GENSETID,
        :LASTCHANGED,
    ],
    :GENUNITS => [
        :GENSETID,
        :VOLTLEVEL,
        :DISPATCHTYPE,
        :STARTTYPE,
        :NORMALSTATUS,
        :MAXCAPACITY,
        :GENSETTYPE,
        :LASTCHANGED,
        :CO2E_EMISSIONS_FACTOR,
        :CO2E_ENERGY_SOURCE,
        :CO2E_DATA_SOURCE,
    ],
    :STATIONOPERATINGSTATUS => [
        :EFFECTIVEDATE,
        :STATIONID,
        :VERSIONNO,
        :STATUS,
    ],
    :STATION => [
        :STATIONID,
        :STATIONNAME,
        :ADDRESS1,
        :ADDRESS2,
        :ADDRESS3,
        :ADDRESS4,
        :CITY,
        :STATE,
        :POSTCODE,
    ]

)
