const FUEL_MAPPING = Dict(
    "Black Coal" => ThermalFuels.COAL,
    "Brown Coal" => ThermalFuels.COAL,
    "Gas" => ThermalFuels.NATURAL_GAS,
    "Liquid Fuel" => ThermalFuels.DISTILLATE_FUEL_OIL,
    "Water" => ThermalFuels.OTHER,
    "Solar" => ThermalFuels.OTHER,
    "Wind" => ThermalFuels.OTHER,
)

const FUEL_PRICES = Dict(
    "Black Coal" => 9.0,
    "Brown Coal" => 9.0,
    "Gas" => 17.0,
    "Liquid Fuel" => 13.0,
    "Water" => 0.0,
    "Solar" => 0.0,
    "Wind" => 0.0,
)

const PM_MAPPING = Dict(
    "Steam Sub Critical" => PrimeMovers.ST,
    "Steam Super Critical" => PrimeMovers.ST,
    "Biomass" => PrimeMovers.ST,
    "CCGT" => PrimeMovers.CC,
    "CCGT Cogen" => PrimeMovers.CC,
    "CCGT - Gas Turbine" => PrimeMovers.CA,
    "CCGT - Steam Turbine" => PrimeMovers.CA,
    "OCGT" => PrimeMovers.GT,
    "Gas-powered steam turbine" => PrimeMovers.GT,
    "Reciprocating Engine" => PrimeMovers.IC,
    "Hydro" => PrimeMovers.HY,
    "Large scale Solar PV" => PrimeMovers.PVe,
    "Wind" => PrimeMovers.WT,
    "Pumped Hydro" => PrimeMovers.PS,
)

const AEMO_PM_MAPPING = Dict(
    "Natural Gas (Pipeline)" => PrimeMovers.CC,
    "Coal seam methane" => PrimeMovers.CC,
    "Coal Seam Methane" => PrimeMovers.CC,
    "Hydro" => PrimeMovers.HY,
    "Wind" => PrimeMovers.WT,
    "Solar" => PrimeMovers.PVe,
    "Brown coal" => PrimeMovers.ST,
    "Black coal" => PrimeMovers.ST,
    "Battery Storage" => PrimeMovers.BA,
    "Diesel oil" => PrimeMovers.IC,
    "Kerosene - non aviation" => PrimeMovers.GT,
    "Landfill biogas methane" => PrimeMovers.CC,
    "Other Biofuels" => PrimeMovers.CC,
    "Bagasse" => PrimeMovers.CC,
    "Coal mine waste gas" => PrimeMovers.CC,
    "Ethane" => PrimeMovers.GT,
    "Biomass and industrial materials" => PrimeMovers.IC,
    "Primary solid biomass fuels" => PrimeMovers.IC,
    "Other solid fossil fuels" => PrimeMovers.IC,
    missing => missing,
)

const AEMO_FUEL_MAPPING = Dict(
    "Black coal" => ThermalFuels.COAL,
    "Brown coal" => ThermalFuels.COAL,
    "Natural Gas (Pipeline)" => ThermalFuels.NATURAL_GAS,
    "Coal seam methane" => ThermalFuels.OTHER_GAS,
    "Coal Seam Methane" => ThermalFuels.OTHER_GAS,
    "Kerosene - non aviation" => ThermalFuels.DISTILLATE_FUEL_OIL,
    "Diesel oil" => ThermalFuels.DISTILLATE_FUEL_OIL,
    "Solar" => ThermalFuels.OTHER,
    "Wind" => ThermalFuels.OTHER,
    "Hydro" => ThermalFuels.OTHER,
    "Battery Storage" => ThermalFuels.OTHER,
    "Landfill biogas methane" => ThermalFuels.AG_BIPRODUCT,
    "Other Biofuels" => ThermalFuels.AG_BIPRODUCT,
    "Primary solid biomass fuels" => ThermalFuels.AG_BIPRODUCT,
    "Bagasse" => ThermalFuels.AG_BIPRODUCT,
    "Coal mine waste gas" => ThermalFuels.OTHER_GAS,
    "Ethane" => ThermalFuels.OTHER_GAS,
    "Biomass and industrial materials" => ThermalFuels.AG_BIPRODUCT,
    "Other solid fossil fuels" => ThermalFuels.WASTE_COAL,
    missing => missing,
)

const NEMWEB_TABLE_SCHEMA = Dict(
    :DISPATCHREGIONSUM => Dict(
        :SETTLEMENTDATE => DateTime,
        :REGIONID => String,
        :TOTALDEMAND => Float64,
        :AVAILABLEGENERATION => Float64,
        :AVAILABLELOAD => Float64,
        :SS_SOLAR_AVAILABILITY => Float64,
        :SS_WIND_AVAILABILITY => Float64,
    ),
    :INTERCONNECTOR => Dict(
        :INTERCONNECTORID => String,
        :REGIONFROM => String,
        :REGIONTO => String,
    ),
    :INTERCONNECTORCONSTRAINT => Dict(
        :FROMREGIONLOSSSHARE => String,
        :EFFECTIVEDATE => DateTime,
        :VERSIONNO => Int,
        :INTERCONNECTORID => String,
        :MAXMWIN => Float64,
        :MAXMWOUT => Float64,
        :LOSSCONSTANT => Float64,
        :LOSSFLOWCOEFFICIENT => Float64,
        :IMPORTLIMIT => Float64,
        :EXPORTLIMIT => Float64,
        :ICTYPE => String,
    ),
    :DUDETAIL => Dict(
        :EFFECTIVEDATE => DateTime,
        :DUID => String,
        :VERSIONNO => Int,
        :CONNECTIONPOINTID => String,
        :VOLTLEVEL => Float64,
        :REGISTEREDCAPACITY => Float64,
        :AGCCAPABILITY => String,
        :DISPATCHTYPE => String,
        :MAXCAPACITY => Float64,
        :STARTTYPE => String,
        :NORMALLYONFLAG => String,
        :SPINNINGRESERVEFLAG => String,
        :INTERMITTENTFLAG => String,
        :SEMISCHEDULE_FLAG => String,
        :MAXRATEOFCHANGEUP => Float64,
        :MAXRATEOFCHANGEDOWN => Float64,
        :ADG_ID => String,
        :MINCAPACITY => Float64,
        :REGISTEREDMINCAPACITY => Float64,
        :MAXRATEOFCHANGEUP_LOAD => Float64,
        :MAXRATEOFCHANGEDOWN_LOAD => Float64,
        :MAXSTORAGECAPACITY => Float64,
        :STORAGEIMPORTEFFICIENCYFACTOR => Float64,
        :STORAGEEXPORTEFFICIENCYFACTOR => Float64,
        :MIN_RAMP_RATE_UP => Float64,
        :MIN_RAMP_RATE_DOWN => Float64,
        :LOAD_MIN_RAMP_RATE_UP => Float64,
        :LOAD_MIN_RAMP_RATE_DOWN => Float64,
        :AGGREGATED => String,
    ),
    :DUDETAILSUMMARY => Dict(
        :DUID => String,
        :START_DATE => Date,
        :END_DATE => Date,
        :DISPATCHTYPE => String,
        :CONNECTIONPOINTID => String,
        :REGIONID => String,
        :STATIONID => String,
        :TRANSMISSIONLOSSFACTOR => Float64,
        :STARTTYPE => String,
        :DISTRIBUTIONLOSSFACTOR => Float64,
        :MINIMUM_ENERGY_PRICE => Float64,
        :MAXIMUM_ENERGY_PRICE => Float64,
        :SCHEDULE_TYPE => String,
        :MIN_RAMP_RATE_UP => Float64,
        :MIN_RAMP_RATE_DOWN => Float64,
        :MAX_RAMP_RATE_UP => Float64,
        :MAX_RAMP_RATE_DOWN => Float64,
        :IS_AGGREGATED => String,
        :LOAD_MINIMUM_ENERGY_PRICE => Float64,
        :LOAD_MAXIMUM_ENERGY_PRICE => Float64,
        :LOAD_MIN_RAMP_RATE_UP => Float64,
        :LOAD_MIN_RAMP_RATE_DOWN => Float64,
        :LOAD_MAX_RAMP_RATE_UP => Float64,
        :LOAD_MAX_RAMP_RATE_DOWN => Float64,
        :SECONDARY_TLF => Float64,
    ),
    :DUALLOC => Dict(
        :VERSIONNO => Int,
        :DUID => String,
        :GENSETID => String,
        :LASTCHANGED => Date,
    ),
    :GENUNITS => Dict(
        :GENSETID => String,
        :VOLTLEVEL => Float64,
        :DISPATCHTYPE => String,
        :STARTTYPE => String,
        :NORMALSTATUS => String,
        :MAXCAPACITY => Float64,
        :GENSETTYPE => String,
        :LASTCHANGED => Date,
        :CO2E_EMISSIONS_FACTOR => Float64,
        :CO2E_ENERGY_SOURCE => String,
        :CO2E_DATA_SOURCE => String,
    ),
    :STATIONOPERATINGSTATUS => Dict(
        :EFFECTIVEDATE => DateTime,
        :STATIONID => String,
        :VERSIONNO => Int,
        :STATUS => String,
    ),
    :STATION => Dict(
        :STATIONID => String,
        :STATIONNAME => String,
        :ADDRESS1 => String,
        :ADDRESS2 => String,
        :ADDRESS3 => String,
        :ADDRESS4 => String,
        :CITY => String,
        :STATE => String,
        :POSTCODE => String,
    )

)
