name: Documentation

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1'

      - name: Cache Julia
        uses: julia-actions/cache@v2

      - name: Cache market data
        uses: actions/cache@v4
        with:
          path: ~/.nemweb_cache
          key: ${{ runner.os }}-nemweb-data-${{ hashFiles('test/fetch_data.jl') }}
          restore-keys: |
            ${{ runner.os }}-nemweb-data-
      - name: Install dependencies
        run: |
          julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate();'

      - name: Fetch data
        shell: julia --project=@. --color=yes {0}
        run: include(joinpath(pwd(), "test", "fetch_data.jl"))

      - name: Render Quarto Project
        run: |
          quarto render docs

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
